### ISSUE TITLE
Build of-dpa/src/example

### ISSUE THREAD

**Issue by vic1231** [Broadcom-Switch/of-dpa#26]
Hello, I'm sorry if this is not the right place for this question, but here it goes anyway.
I'm new with OF-DPA SDK. And I have saw some document like OFDPA_ASSV-ETP200-R.pdf and of-dpa/doc/html.
I want to build src/example for a build test.
Is this package can build independent in OS?
When I enter to src/example folder, then rename Makefile.example to Makefile.
Then marked line CROSS_COMPILE_GTO(# CROSS_COMPILE_GTO = /projects/nwsoft-toolchains/brl/brl_2.0/brl_2.0.1/gto/bin/powerpc-broadcom-linux-gnu-).
It means general gcc building.
After I type make command, build error messages was appeared:

---------------------------------------
$ make
gcc -o client_routing -L../../bin/gto-trident-brl20 -Wl,-Bstatic client_routing.o -Wl,-Bdynamic -lc -lrpc_client
/usr/bin/ld: skipping incompatible ../../bin/gto-trident-brl20/librpc_client.so when searching for -lrpc_client
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../lib/librpc_client.so when searching for -lrpc_client
/usr/bin/ld: skipping incompatible /usr/lib/../lib/librpc_client.so when searching for -lrpc_client
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../librpc_client.so when searching for -lrpc_client
/usr/bin/ld: skipping incompatible /usr/local/lib/librpc_client.so when searching for -lrpc_client
/usr/bin/ld: skipping incompatible /usr/lib/librpc_client.so when searching for -lrpc_client
/usr/bin/ld: cannot find -lrpc_client
collect2: error: ld returned 1 exit status
Makefile:60: recipe for target 'client_routing' failed
make: *** [client_routing] Error 1

---------------------------------------
Does anyone knows how to solve this issue?
* /usr/bin/ld: cannot find -lrpc_client

Why I want to build it is because I don't have a u-boot, my CPU architecture is X86_64.
So I can't not follow of-dpa/bin/gto-trident-brl20 steps to update bootloader.
I think OF-DPA support x86_64, isn't it?
But is there anyone knows how to start with build OF-DPA? 
Or maybe it needs broadcom's tool chain like powerpc-broadcom-linux-gnu-gcc?

**Comment by HamadiSE** [comment]
Hi,
I don't have an answer for your question. But it seems you have the compiler ?
how did you get it ?
is it available on internet ?

**Comment by vic1231** [comment]
I just have my project cross compiler, not brcm's compiler(ex, powerpc-broadcom-linux-gnu-gcc). I want use my own cross compiler to build it.

**Comment by simonknee** [comment]
You can use your own compiler but you will need to get access to the Broadcom SDK.  Your Broadcom sales representative should be able to help you.

**Comment by vic1231** [comment]
Okay, I will check to sales, thanks for help.

**Comment by ahmedcs** [comment]
Hello simon,

May you guide me on how to get contact with broadcom in terms of the broadcom switch SDK and OF-DPA stuff?!

Thanks and Best Regards,

**Comment by simonknee** [comment]
Hi Ahmed,

Send me your email address or connect with me on LinkedIn and I can get you in touch with the right people.

Regards,

Simon.

**Comment by ahmedcs** [comment]
@simonknee 

Thanks for the reply, i tried to connect with you on linkedin (asks for your email)

my official email is amas@cse.ust.hk, my public email is ahmedcs982@gmail.com

Thanks

**Comment by Voskrese** [comment]
так же не пойму, где скачать broadcom SDK, а скорее toolchain, но меня интересует mipsel
а так же, в чем суть замены "BUILD_PLATFORM=ELDK" ELDK на WR_LINUX ?

**Comment by simonknee** [comment]
Not sure I am answering your question, but some toolchains are available from your Broadcom representative once a software license agreement is signed.  Wind River Linux is not supported.
