### ISSUE TITLE
Trident II(BCM56854_A2)

### ISSUE THREAD

**Issue by HamadiSE** [Broadcom-Switch/of-dpa#27]
Hi, 
I'm new to this environment of devopment, 
How do I need to start developping application for a switch based on Trident II(BCM56854_A2).
The document provided about installing is noting only quanta LY2, would the same files works for LY6 ?

I can't try it myself before having an idea. I don't want to risk broking the switch, it's the only that i have unfortunatly, 
best regards

**Comment by simonknee** [comment]
For GitHub we only support LY2, not LY6, sorry.  Quanta or your Broadcom sales representative should be able to provide further information on LY6 support.

**Comment by kelleyk** [comment]
Is there a hardware compatibility list somewhere?
