### ISSUE TITLE
OF-DPA sandbox 

### ISSUE THREAD

**Issue by mancubus77** [Broadcom-Switch/of-dpa#33]
Hi, All

Can I launch OF-DPA on x86 or qemu emulation? I need to develop a few scripts for bcm ttp, but don't want to be stick with a switch.

**Comment by simonknee** [comment]
Unfortunately OF-DPA is only supported on switch platforms at this point in time.  See the documentation and the bin directory for which switch platforms are supported.

**Comment by mancubus77** [comment]
Thank you, the answer was predictable.
