### ISSUE TITLE
Error -23 inserting flows into the VLAN1 table

### ISSUE THREAD

**Issue by jpillora** [Broadcom-Switch/of-dpa#36]
Hi there,

My team and I are currently using OF-DPA (`version 2.0.2.0 -- Built on Mon Sep 14 2015 at 05:51:48 UTC`) to develop an automated routing platform we're attempting to use OF-DPA to match double-tagged 802.1Q (QinQ). Based on the OF-DPA documentation, we need to match the outer tag on the VLAN table and then match the inner tag using the VLAN1 table.

Here's our functional Python example, forked off the provided examples:

*edited* 12/5/16 1:55AM UTC - the code below now correctly inserts flows and returns `success`

``` python
#! /usr/bin/env python

"""
OF-DPA Match QinQ example
Usage: ./qinq.py [add|delete]
Author: Jaime Pillora <jaime.pillora@ordnance.io>
"""

from OFDPA_python import *
import sys

def errstr(rc):
    if rc == OFDPA_E_EXISTS:
        return "already exists"
    elif rc == OFDPA_E_ERROR:
        return "constraint violated"
    elif rc == OFDPA_E_NONE:
        return "none"
    return "error (%d)" % (rc)

def main():
    rc = ofdpaClientInitialize("OFDPA_example")
    if rc != OFDPA_E_NONE:
        print "Unable to initialize."
        return
    # settings
    action = "add"
    if len(sys.argv) == 2:
        action = sys.argv[1]
    ofdpaFlowFn = None
    if action == "add":
        ofdpaFlowFn = ofdpaFlowAdd
    elif action == "delete":
        ofdpaFlowFn = ofdpaFlowDelete
    else:
        print "unknown action"
        return
    TRUE = 1
    # qinq configuration
    COOKIE = 0xdeadbeef
    IN_PORT = 38
    OUTER_VLAN = 2
    INNER_VLAN = 555
    TEMP_VLAN = 2003
    NEW_PORT = 39
    NEW_VLAN = 100
    print "%s flows on port %d..." % (action, IN_PORT)
    #=================================
    # Match on VLAN Table
    #  IN_PORT = $PORT
    #  VLAN_VID = $OUTER
    #  ACTIONS
    #     POP_VLAN
    #     SET FIELD `OVID=$OUTER`
    #     GO TO VLAN 1 TABLE (edited)
    outer = ofdpaFlowEntry_t()
    ofdpaFlowEntryInit(OFDPA_FLOW_TABLE_ID_VLAN, outer)
    outer.cookie = COOKIE
    outer.priority = 0x8000
    outer.flowData.vlanFlowEntry.match_criteria.inPort = IN_PORT
    outer.flowData.vlanFlowEntry.match_criteria.vlanId = (OFDPA_VID_PRESENT | OUTER_VLAN)
    outer.flowData.vlanFlowEntry.match_criteria.vlanIdMask = (OFDPA_VID_PRESENT | OFDPA_VID_EXACT_MASK)
    outer.flowData.vlanFlowEntry.popVlanAction = TRUE
    outer.flowData.vlanFlowEntry.ovidAction = TRUE
    outer.flowData.vlanFlowEntry.ovid = OUTER_VLAN
    outer.flowData.vlanFlowEntry.gotoTableId = OFDPA_FLOW_TABLE_ID_VLAN_1
    print "[table %d] outer VLAN %d -> table %d" % (outer.tableId, OUTER_VLAN, outer.flowData.vlanFlowEntry.gotoTableId)
    rc = ofdpaFlowFn(outer)
    if rc != OFDPA_E_NONE and rc != OFDPA_E_EXISTS:
        print "  outer: %s" % errstr(rc)
        return
    #=================================
    # Match on VLAN 1 Table
    #   IN_PORT = $PORT
    #   VLAN_VID = $INNER
    #   OVID = $OUTER
    #   ACTION
    #      SET VLAN_VID $TEMP_VLAN
    #      GOTO TABLE = TERMINATION_MAC
    inner = ofdpaFlowEntry_t()
    rc = ofdpaFlowEntryInit(OFDPA_FLOW_TABLE_ID_VLAN_1, inner)
    if rc != OFDPA_E_NONE:
        print "inner init: %s" % errstr(rc)
        return
    inner.cookie = COOKIE
    inner.priority = 0x8000
    inner.flowData.vlan1FlowEntry.match_criteria.inPort = IN_PORT
    inner.flowData.vlan1FlowEntry.match_criteria.ovid = (OFDPA_VID_PRESENT | OUTER_VLAN)
    inner.flowData.vlan1FlowEntry.match_criteria.vlanId = (OFDPA_VID_PRESENT | INNER_VLAN)
    inner.flowData.vlan1FlowEntry.setVlanIdAction = TRUE
    inner.flowData.vlan1FlowEntry.newVlanId = TEMP_VLAN
    inner.flowData.vlan1FlowEntry.popVlanAction = TRUE
    inner.flowData.vlan1FlowEntry.pushVlanAction = TRUE
    inner.flowData.vlan1FlowEntry.newTpid = 0x8100
    inner.flowData.vlan1FlowEntry.gotoTableId = OFDPA_FLOW_TABLE_ID_TERMINATION_MAC
    print "[table %d] inner VLAN %d -> table %d!" % (inner.tableId, INNER_VLAN, inner.flowData.vlan1FlowEntry.gotoTableId)
    rc = ofdpaFlowFn(inner)
    if rc != OFDPA_E_NONE and rc != OFDPA_E_EXISTS:
        print "  inner: %s" % errstr(rc)
        return
    #=================================
    # TODO
    # Match on TERMINATION_MAC Table
    #    IN_PORT = $PORT
    #    VLAN_VID = $TEMP_VLAN
    #    ACTION
    #       VLAN_VID = $NEW_VLAN
    #       OUT_PORT = $NEW_PORT
    print "success"
    return

if __name__ == '__main__': main()
```

At the moment, the `outer` flow is inserting correctly, though `inner` flow is failing with `-23` (Constraint violated) though we can't figure out what's wrong with the flow and we've tried many variations of it.

Any help or link to a working QinQ python example would be greatly appreciated!

Regards,
Jaime Pillora
Ordnance Networks

**Comment by jpillora** [comment]
Hi @dpbouchard, @volodymyr-samotiy and @vitalivanov - any ideas with this?

**Comment by dpbouchard** [comment]
Dear Jaime,

I believe that in order for this to work, you need to use the OFDPA_VID_PRESENT bit for the VLAN IDs in the VLAN 1 flow entry match criteria (as you did for the VLAN flow table).

Let me know if this doesn't solve your issue.

Best Regards,
Don Bouchard
Broadcom OF-DPA Development Manager

**Comment by jpillora** [comment]
Wow, I should have seen that! Seems to be correctly inserting now 😄! Can't test the flow with traffic yet, though I'm sure it'll be fine when I do. Will re-open if I have anymore issues. Thanks Don, much appreciated!

**Comment by jpillora** [comment]
Since I'm getting the same error on a similar problem, I thought I'd just re-open. I just tried creating a flow for an untagged port using the code below and running it also yields `-23`:

``` python
#! /usr/bin/env python

"""
OF-DPA Match untagged example
Usage: ./untagged.py
Author: Jaime Pillora <jaime.pillora@ordnance.io>
"""

from OFDPA_python import *
import sys

def errstr(rc):
    if rc == OFDPA_E_EXISTS:
        return "already exists"
    elif rc == OFDPA_E_ERROR:
        return "constraint violated"
    elif rc == OFDPA_E_NONE:
        return "none"
    return "error (%d)" % (rc)

def main():
    rc = ofdpaClientInitialize("OFDPA_example")
    if rc != OFDPA_E_NONE:
        print "Unable to initialize."
        return
    # settings
    action = "add"
    if len(sys.argv) == 2:
        action = sys.argv[1]
    ofdpaFlowFn = None
    if action == "add":
        ofdpaFlowFn = ofdpaFlowAdd
    elif action == "delete":
        ofdpaFlowFn = ofdpaFlowDelete
    else:
        print "unknown action"
        return
    TRUE = 1
    # untagged configuration
    COOKIE = 0xdeadbeef
    IN_PORT = 40
    #NEW_PORT = 39
    NEW_VLAN = 100
    #=================================
    # DOCS: Untagged Packet Port VLAN Assignment
    # Exact match on IN_PORT and VLAN id == 0 (lower 12 bits of match field)
    # value using a mask value of 0x0fff (masks off OFPVID_PRESENT). Action set
    # must assign a VLAN_VID. The VLAN_VID value cannot be used in a VLAN
    # Filtering rule. If the packet does not have a VLAN tag, one will be pushed
    # if necessary at packet egress. Rule must have a Goto-Table instruction
    # specifying the Termination MAC Flow Table. Untagged packets are
    # dropped if there is no port VLAN assignment rule. Can optionally assign a
    # VRF for routed packets.
    flow = ofdpaFlowEntry_t()
    rc = ofdpaFlowEntryInit(OFDPA_FLOW_TABLE_ID_VLAN, flow)
    if rc != OFDPA_E_NONE:
        print "init: %s" % errstr(rc)
        return
    # flow.cookie = COOKIE
    # flow.priority = 0x8000
    flow.flowData.vlanFlowEntry.gotoTableId = OFDPA_FLOW_TABLE_ID_TERMINATION_MAC
    flow.flowData.vlanFlowEntry.match_criteria.inPort = IN_PORT
    flow.flowData.vlanFlowEntry.match_criteria.vlanId = (OFDPA_VID_NONE)
    flow.flowData.vlanFlowEntry.match_criteria.vlanIdMask = (OFDPA_VID_EXACT_MASK)
    flow.flowData.vlanFlowEntry.setVlanIdAction = TRUE
    flow.flowData.vlanFlowEntry.newVlanId = NEW_VLAN
    print "[table %d] untagged port %d -> add vlan %d -> table %d" % (flow.tableId, IN_PORT, flow.flowData.vlanFlowEntry.newVlanId, flow.flowData.vlanFlowEntry.gotoTableId)
    rc = ofdpaFlowFn(flow)
    if rc != OFDPA_E_NONE and rc != OFDPA_E_EXISTS:
        print "  flow: %s" % errstr(rc)
        return
    print "success"
    return

if __name__ == '__main__': main()
```

```
$ ./untagged.py
[table 10] untagged port 40 -> add vlan 100 -> table 20
  flow: constraint violated
```

Cheers,
Jaime

**Comment by dpbouchard** [comment]
Dear Jaime,

Sorry you're still having issues, my team is looking into your issue and I will get back to you as soon as I have some news.

Also, I'm not sure you're doing this, but one thing that can help in debugging is to turn on client debug logging and setting the appropriate logging level.  You can do this by executing the 2 client apps, client_debuglvl and client_debugcomp.

To get help on these apps, you can simply run them with a '--help' on the command line to see the correct command usage.

Hope this helps also.

Best regards,
Don Bouchard
Broadcom OF-DPA Development Manager

**Comment by jpillora** [comment]
Hi Don,

Thanks for the tip, though we have tried setting log levels and it appears to only set the log output of the `ofagentapp` (`/var/log/ofagentapp.log`). Since python calls using the RPC API don't seem to pass through the OF agent, there are no logs generated from running python code. I may have missed something though!

Cheers,
Jaime

**Comment by dpbouchard** [comment]
Dear Jaime,

vlanIdMask is incorrect in the script. It needs to be (OFDPA_VID_PRESENT | OFDPA_VID_EXACT_MASK) for untagged Vlan Flow.

Let me know if this fixes the problem.

Best regards,
Don Bouchard
Broadcom OF-DPA Development Manager

**Comment by jpillora** [comment]
Hi Don,
We just tried it and it still gave us -23
Cheers!
Jaime

**Comment by dpbouchard** [comment]
Hi Jaime,

Sorry that didn't help.  For your reference, I took the following JSON from the TTP that defines what must be done for untagged VLAN packets

"{""action"": ""PUSH_VLAN"",""ethertype"": ""0x8100""},
{ ""action"": ""SET_FIELD"", ""field"": ""VLAN_ID"", ""value"":  ""<port_vid>|0x1000"" },
{""zero_or_one"": [ { ""all"" : [ {""action"": ""PUSH_VLAN"",""ethertype"": ""0x8100""},
             { ""action"": ""SET_FIELD"", ""field"": ""VLAN_ID"", ""value"":  ""<port_vid_2>|0x1000"" }  ]  } ] },
{""zero_or_one"": [ { ""action"": ""SET_FIELD"", ""field"": ""$VRF"", ""value"":  ""<vrf>"" }]}"

Let me know if this helps you at all.

Best regards,
Don Bouchard
Broadcom OF-DPA Development Manager

**Comment by jpillora** [comment]
Hi Don,
Thanks for the info, I also found it [here](https://github.com/Broadcom-Switch/of-dpa/blob/master/ofdpa-2.01-16-feb-2016.json#L2237-L2265) though unfortunately I was still not able to get it working.

I tried adding:
``` py
    flow.flowData.vlanFlowEntry.pushVlan2Action = TRUE
    flow.flowData.vlanFlowEntry.newTpid2 = 0x8100
```

to the `untagged.py` example above to no avail. I'm guessing those are the most appropriate [struct fields](https://github.com/Broadcom-Switch/of-dpa/blob/master/src/include/ofdpa_datatypes.h#L629-L630) to `PUSH_VLAN`.

I also tried going via `ofagent` using `ovs-ofctl` though it has client-side flow validation and rejects it:
``` sh
$ ovs-ofctl --protocol OpenFlow13 add-flow tcp:<ip>:<port> "table=10,in_port=40,dl_vlan=0,actions=push_vlan:0x8100,set_vlan_vid:100,goto_table:20"
ovs-ofctl: actions are invalid with specified match (OFPBAC_BAD_TAG)
```

Do you have any working examples you could pass along (can be in any language)?

Cheers
Jaime

**Comment by vitalivanov** [comment]
@jpillora @alexanderturner @dpbouchard 

To start OF-DPA in debug mode do the following under Interface Masters platforms:

```
$ cd /broadcom
$ ./startup-ofdpa.sh --help
Usage: bash startup-ofdpa.sh TOOL [-h] [TOOL_OPTIONS]
 TOOL       One of two OF-DPA daemons - ofagentapp or ofdpa
 -h         This help

IMT OF-DPA Startup Script.

Example of running ofagentapp:
bash startup-ofdpa.sh ofagentapp -l 192.168.0.1:6634 -t 192.168.0.2:6633

Example of running ofdpa:
bash startup-ofdpa.sh ofdpa -c 1 -c 2 -c 3 -c 4 -c 5 -d 2
```

Once I started it with command:
```
$ cd /broadcom
$ bash startup-ofdpa.sh ofdpa -c 1 -c 2 -c 3 -c 4 -c 5 -d 2
```

I saw description of failure on console screen when running original script:
```
ofdbFlowVlanEntryValidate: Invalid vlanId/mask combination. vlanId = 0 (0x0), vlanIdMask = 0x1000
ofdpaFlowAdd: Table ID 10 flow entry did not pass validation.
```

When modified with what @dpbouchard proposed (OFDPA_VID_PRESENT | OFDPA_VID_EXACT_MASK)  :
```
ofdbFlowVlanEntryValidate: Entry specifies newVlanId without OFDPA_VID_PRESENT bit set. setVlanIdAction = 1, newVlanId = 0x64
ofdpaFlowAdd: Table ID 10 flow entry did not pass validation.
```

If I change the code to be:
```
-    flow.flowData.vlanFlowEntry.newVlanId = NEW_VLAN
+    flow.flowData.vlanFlowEntry.newVlanId = NEW_VLAN | OFDPA_VID_PRESENT
```
Then I can see the following problem:
```
ofdbFlowVlanEntryValidate: untagged flow rejected: flow admitting tagged traffic on port/VLAN not found. port = 40. vlanId = 100
ofdpaFlowAdd: Table ID 10 flow entry did not pass validation.
```

@dpbouchard do we need to install any flows before?

**Comment by dpbouchard** [comment]
Yes, you do need to install a flow before.  Sorry for not catching this earlier.  Please install the vlan filtering rule before installing the untagged vlan rule. This is the problem as per the logs.

Best regards,
Don Bouchard
Broadcom OF-DPA Development Manager

**Comment by jpillora** [comment]
Thanks @vitalivanov, will try that now 😊 

Hi @dpbouchard,

Just confirming, is the this "vlan filtering rule" you're referring to:

> **VLAN Table**
> VLAN Filtering
> Exact match on IN_PORT and VLAN_VID parsed from the packet. For tagged packets with a VLAN tag containing a VLAN_VID greater than zero. Cannot be masked. VLAN_VID cannot be used in a Port VLAN Assignment rule for untagged packets. The only instruction is Goto-Table and must specify the Termination MAC Flow Table. Tagged packets that do not match any rule are treated as VLAN_VIDs that are not allowed on the port and are dropped. Can optionally assign a VRF for routed packets.

Or do you mean L2 Interface Group Entries ("egress vlan filtering")? If so, I assume this also means we'll need a flow in the Policy ACL table to link it to this new L2 Int group?

Cheers,
Jaime

**Comment by dpbouchard** [comment]
It is Rule#1 in “VLAN Flow”.

Port VLAN Assignment (Untagged Packet)

Exact match on IN_PORT and OFPVID_NONE. Action set must push a VLAN tag and assign a valid VLAN_VID. Optionally it can push another tag and set a new outermost VLAN Id. Note that before installing the Port VLAN Assignment rule there must already be a VLAN Filtering rule for the IN_PORT and outermost VLAN_VID. A Port VLAN Assignment Rule must have a Goto-Table instruction specifying the Termination MAC Flow Table. Untagged packets may be dropped if there is no VLAN assignment rule for the ingress port. Can optionally assign a VRF for routed packets.

Let me know if this works for you.

Best regards,
Don Bouchard
Broadcom OF-DPA Development Manager

**Comment by jpillora** [comment]
Hi @dpbouchard, that did it :) I had an older copy of the documentation.

I'm now having issues outputting untagged packets. Before I go into the DC patch in a debug interface, I'll just confirm with you I'm on the right track. I've got an ACL Table entry, matching `Port 6` and `VLAN 4004`, linked to this group:

```
groupId = 0x0fa40028 (L2 Interface, VLAN ID = 4004, Port ID = 40): duration: 635, refCount:1
	bucketIndex = 0: outputPort = 40 popVlanTag = 1
```

Is this the correct way to output untagged packets on a port?

**Comment by dpbouchard** [comment]
Dear Jaime,

You are correct, you have  the correct way to output untagged packets on a port.

The following L2 interface group with popVlanTag=1 outputs the egress packets untagged. This can be achieved by referencing the L2 interface group to either ACL flow entry or bridging flow entry.
 
groupId = 0x0fa40028 (L2 Interface, VLAN ID = 4004, Port ID = 40): duration: 635, refCount:1
    bucketIndex = 0: outputPort = 40 popVlanTag = 1
 
Also, thanks for the comment about the bridging use-case.  I'll look into that for our next release.

Thanks,
Don Bouchard

**Comment by jpillora** [comment]
Hi Don,
I just confirmed that we've got both untagged and double tagged flows now working. Thanks for all your help :)
Regards,
Jaime Pillora
