### ISSUE TITLE
Pop single-tag on egress

### ISSUE THREAD

**Issue by jpillora** [Broadcom-Switch/of-dpa#39]
I'm trying to convert a single-tagged frame into an untagged frames using the `OFDPA_FLOW_TABLE_ID_EGRESS_VLAN` table. I'm attempting to make use of `ofdpaEgressVlanFlowEntry_s`'s `popVlanAction` field:

```
outPort = 1
vlanId = (OFDPA_VID_PRESENT | 4)
vlanIdMask = (OFDPA_VID_PRESENT | OFDPA_VID_EXACT_MASK)
allowVlanTranslation = OFDPA_TRUE
popVlanAction = OFDPA_TRUE
```

Though with debug logging enabled, I'm getting:

```
ofdbFlowEgressVlanEntryValidate: VLAN Translate Single Tag type entry specifies invalid action.
````

Note:

* I've previously added the L2 Unfiltered Port group entry to allow use of the egress tables
* OFDPA `version 2.0.4.0 -- Built on Mon Apr 25 2016 at 09:25:01 UTC`
* Pop VLAN works when done via an L2 Interface group though I want the port to be unfiltered

I'm quite sure I'm missing something though the way the docs read, it appears as if I can only go from double-tagged to untagged using egress tables 0 and 1, though that seems strange. What's the correct way to output untagged frames using the egress tables?

**Comment by toanju** [comment]
Afaik this is currently not working on unfiltered egress ports. You only can use the pop action on a filtered egress interface.

**Comment by jpillora** [comment]
Thanks for the clarification
