### ISSUE TITLE
Problem with Ryu simple_switch_13.py application

### ISSUE THREAD

**Issue by fradensky** [Broadcom-Switch/of-dpa#6]
Hi,

I'm trying to run Ruy simple_switch_13.py application on controller communicating 
with of-dpa 1.0.0.1 agent and get the following error:

indigo_ofdpa_driver: ERROR: Unsupported instruction of_instruction_apply_actions for flow table 0.
indigo_ofdpa_driver: ERROR: Failed to get flow instructions. (err = -5)

Is this a known issue ? How can I fix it ?

Thanks.

Felix Radensky.

**Comment by tengiao** [comment]
Hi, 

I'm running OFDPA on Broadcom's BCM 956260 white box switch. I'm looking to experiment with applications/scripts that have already been successfully tested on StrataXGS Trident boards.  

When trying out Vitaliy's simple_switcg_13.py, I've got this:

indigo_ofdpa_driver: ERROR: Error in adding Group bucket

and I'm trying to understand how and why the OFDPA_E_NONE variable was set to 0. I'm still fumbling to understand what could have triggered OFDPA_E_NONE. So if you have any views on this, please feel free to share.

Cheers!
Miao

**Comment by tengiao** [comment]
Further to my comment above, the error was flagged by the indigo ofagent.
